// Code generated by tools/split_swagger. DO NOT EDIT.
package seller

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "description": "API For Seller Management Portal",
        "title": "Seller API Portal",
        "version": "2.0"
    },
    "host": "localhost:3000",
    "basePath": "/api/v2",
    "paths": {
        "/seller/categories": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Create a new product category as seller",
                "parameters": [
                    {
                        "description": "Category Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_seller.createCategoryReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Seller Create Category",
                "tags": [
                    "Seller Products"
                ]
            }
        },
        "/seller/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Login to Seller Portal",
                "parameters": [
                    {
                        "description": "Login Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.LoginReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "summary": "Seller Login",
                "tags": [
                    "Seller Auth"
                ]
            }
        },
        "/seller/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Revoke seller refresh token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.RefreshTokenReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "summary": "Seller Logout",
                "tags": [
                    "Seller Auth"
                ]
            }
        },
        "/seller/products": {
            "get": {
                "description": "List products created by logged in seller",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "items": {
                                "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.Product"
                            },
                            "type": "array"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List Seller Products",
                "tags": [
                    "Seller Products"
                ]
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Add a new product for seller store",
                "parameters": [
                    {
                        "description": "Create Product Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.CreateProductReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Create Product",
                "tags": [
                    "Seller Products"
                ]
            }
        },
        "/seller/products/{id}": {
            "delete": {
                "description": "Delete a product owned by seller",
                "parameters": [
                    {
                        "description": "Product ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Delete Product",
                "tags": [
                    "Seller Products"
                ]
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "description": "Update existing seller product details",
                "parameters": [
                    {
                        "description": "Product ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "description": "Update Product Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.UpdateProductReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Update Product",
                "tags": [
                    "Seller Products"
                ]
            }
        },
        "/seller/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Refresh seller access token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.RefreshTokenReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "summary": "Seller Refresh Token",
                "tags": [
                    "Seller Auth"
                ]
            }
        }
    },
    "definitions": {
        "github_com_l0ng7h0r_ecommerce_internal_domain.AuthResponse": {
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "roles": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "user_id": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.Category": {
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.CreateProductReq": {
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "stock": {
                    "type": "integer"
                }
            },
            "required": [
                "name",
                "price",
                "stock"
            ],
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.LoginReq": {
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            },
            "required": [
                "email",
                "password"
            ],
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.Product": {
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "seller_id": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.RefreshTokenReq": {
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            },
            "required": [
                "refresh_token"
            ],
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.UpdateProductReq": {
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "stock": {
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "internal_handler_seller.createCategoryReq": {
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ],
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "in": "header",
            "name": "Authorization",
            "type": "apiKey"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "Seller API Portal",
	Description:      "API สำหรับร้านค้า: เข้าสู่ระบบ จัดการสินค้า สร้างหมวดหมู่",
	InfoInstanceName: "seller",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
