// tools/split_swagger/main.go
// Run: go run ./tools/split_swagger/...
// แยก swagger JSON ตาม path prefix (/user, /seller, /admin) แล้วสร้าง _docs.go ใหม่ต่อ portal
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"
)

// SwaggerDoc represents a minimal swagger 2.0 document
type SwaggerDoc struct {
	Swagger             string                 `json:"swagger"`
	Info                map[string]interface{} `json:"info"`
	Host                string                 `json:"host"`
	BasePath            string                 `json:"basePath"`
	Paths               map[string]interface{} `json:"paths"`
	Definitions         map[string]interface{} `json:"definitions"`
	SecurityDefinitions map[string]interface{} `json:"securityDefinitions,omitempty"`
}

// portalConfig defines each portal's filtering criteria
type portalConfig struct {
	Name        string
	PathPrefix  string
	Title       string
	Description string
	OutputDir   string
	PackageName string
}

var portals = []portalConfig{
	{
		Name:        "user",
		PathPrefix:  "/user/",
		Title:       "Customer API Portal",
		Description: "API for customer registration, login, product browsing, shopping cart, ordering and payment",
		OutputDir:   "docs/user",
		PackageName: "user",
	},
	{
		Name:        "seller",
		PathPrefix:  "/seller/",
		Title:       "Seller API Portal",
		Description: "API for seller registration, login, product management and category management",
		OutputDir:   "docs/seller",
		PackageName: "seller",
	},
	{
		Name:        "admin",
		PathPrefix:  "/admin/",
		Title:       "Admin Management Portal",
		Description: "API for admin management, including user management, product management, category management, and order management",
		OutputDir:   "docs/admin",
		PackageName: "admin",
	},
}

// docsTemplate is the Go source template for each portal's _docs.go
const docsTemplate = `// Code generated by tools/split_swagger. DO NOT EDIT.
package {{.PackageName}}

import "github.com/swaggo/swag"

const docTemplate = ` + "`{{.SwaggerJSON}}`" + `

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "{{.Title}}",
	Description:      "{{.Description}}",
	InfoInstanceName: "{{.Name}}",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{"{{"}}",
	RightDelim:       "{{"}}"}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
`

type tmplData struct {
	PackageName string
	SwaggerJSON string
	Title       string
	Description string
	Name        string
}

func main() {
	// Read the master swagger JSON (user_swagger.json has all routes after swag init)
	masterPath := "docs/user/user_swagger.json"
	data, err := os.ReadFile(masterPath)
	if err != nil {
		log.Fatalf("❌ Cannot read master swagger JSON at %s: %v\n   ➜ Run: swag init -g cmd/api/main.go -o docs/user --instanceName user --parseDependency", masterPath, err)
	}

	var master SwaggerDoc
	if err := json.Unmarshal(data, &master); err != nil {
		log.Fatalf("❌ Failed to parse swagger JSON: %v", err)
	}

	for _, portal := range portals {
		log.Printf("🔧 Processing portal: %s (prefix: %s)", portal.Name, portal.PathPrefix)

		// 1. Filter paths by prefix
		filteredPaths := map[string]interface{}{}
		for path, spec := range master.Paths {
			if strings.HasPrefix(path, portal.PathPrefix) {
				filteredPaths[path] = spec
			}
		}
		log.Printf("   Found %d routes for %s portal", len(filteredPaths), portal.Name)

		// 2. Collect all $ref definition names used in filtered paths
		usedRefs := collectRefs(filteredPaths)

		// 3. Filter definitions — include referenced ones + their nested refs
		filteredDefs := map[string]interface{}{}
		// Two passes to catch nested definitions
		for i := 0; i < 2; i++ {
			for defName, defSpec := range master.Definitions {
				if usedRefs[defName] {
					filteredDefs[defName] = defSpec
					for ref := range collectRefs(defSpec) {
						usedRefs[ref] = true
					}
				}
			}
		}

		// 4. Build filtered swagger doc
		filtered := SwaggerDoc{
			Swagger:             "2.0",
			Host:                master.Host,
			BasePath:            master.BasePath,
			SecurityDefinitions: master.SecurityDefinitions,
			Info: map[string]interface{}{
				"title":       portal.Title,
				"description": portal.Description,
				"contact":     map[string]interface{}{},
				"version":     "2.0",
			},
			Paths:       filteredPaths,
			Definitions: filteredDefs,
		}

		// 5. Marshal to JSON
		jsonBytes, err := json.MarshalIndent(filtered, "", "    ")
		if err != nil {
			log.Fatalf("❌ Failed to marshal filtered swagger for %s: %v", portal.Name, err)
		}

		// Escape backticks in JSON for Go raw string safety
		jsonStr := strings.ReplaceAll(string(jsonBytes), "`", "`+\"`\"+`")

		// 6. Write output directory + swagger.json
		if err := os.MkdirAll(portal.OutputDir, 0o755); err != nil {
			log.Fatalf("❌ Failed to create output dir %s: %v", portal.OutputDir, err)
		}

		jsonOutPath := fmt.Sprintf("%s/%s_swagger.json", portal.OutputDir, portal.Name)
		if err := os.WriteFile(jsonOutPath, jsonBytes, 0o644); err != nil {
			log.Fatalf("❌ Failed to write swagger JSON for %s: %v", portal.Name, err)
		}
		log.Printf("   ✅ Written: %s", jsonOutPath)

		// 7. Generate docs.go from template
		tmpl, err := template.New("docs").Parse(docsTemplate)
		if err != nil {
			log.Fatalf("❌ Failed to parse docs template: %v", err)
		}

		docsOutPath := fmt.Sprintf("%s/%s_docs.go", portal.OutputDir, portal.Name)
		f, err := os.Create(docsOutPath)
		if err != nil {
			log.Fatalf("❌ Failed to create docs.go for %s: %v", portal.Name, err)
		}

		if err := tmpl.Execute(f, tmplData{
			PackageName: portal.PackageName,
			SwaggerJSON: jsonStr,
			Title:       portal.Title,
			Description: portal.Description,
			Name:        portal.Name,
		}); err != nil {
			f.Close()
			log.Fatalf("❌ Failed to execute template for %s: %v", portal.Name, err)
		}
		f.Close()
		log.Printf("   ✅ Written: %s", docsOutPath)
	}

	log.Println("\n🎉 Done! Swagger docs split successfully.")
	log.Println("   User Portal   → docs/user/")
	log.Println("   Seller Portal → docs/seller/")
	log.Println("   Admin Portal  → docs/admin/")
}

// collectRefs extracts all $ref definition names from any JSON structure
func collectRefs(v interface{}) map[string]bool {
	refs := map[string]bool{}
	collectRefsRecursive(v, refs)
	return refs
}

func collectRefsRecursive(v interface{}, refs map[string]bool) {
	switch node := v.(type) {
	case map[string]interface{}:
		for k, val := range node {
			if k == "$ref" {
				if refStr, ok := val.(string); ok {
					// Format: "#/definitions/SomeName"
					parts := strings.Split(refStr, "/")
					if len(parts) == 3 && parts[1] == "definitions" {
						refs[parts[2]] = true
					}
				}
			} else {
				collectRefsRecursive(val, refs)
			}
		}
	case []interface{}:
		for _, item := range node {
			collectRefsRecursive(item, refs)
		}
	}
}
