// Code generated by tools/split_swagger. DO NOT EDIT.
package admin

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "description": "API For Admin Management Portal",
        "title": "Admin Management Portal",
        "version": "2.0"
    },
    "host": "localhost:3000",
    "basePath": "/api/v2",
    "paths": {
        "/admin/categories": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Create a new product category",
                "parameters": [
                    {
                        "description": "Category Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.createCategoryReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Create Category",
                "tags": [
                    "Admin Categories"
                ]
            }
        },
        "/admin/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Login to Admin Management Portal",
                "parameters": [
                    {
                        "description": "Login Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.LoginReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "summary": "Admin Login",
                "tags": [
                    "Admin Auth"
                ]
            }
        },
        "/admin/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Revoke admin refresh token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.RefreshTokenReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "summary": "Admin Logout",
                "tags": [
                    "Admin Auth"
                ]
            }
        },
        "/admin/orders": {
            "get": {
                "description": "Get list of all orders across the system",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "items": {
                                "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.Order"
                            },
                            "type": "array"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List All System Orders",
                "tags": [
                    "Admin Order Management"
                ]
            }
        },
        "/admin/orders/{id}/status": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "description": "Update processing status of an order",
                "parameters": [
                    {
                        "description": "Order ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "description": "Update Status Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.UpdateOrderStatusReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Update Order Status",
                "tags": [
                    "Admin Order Management"
                ]
            }
        },
        "/admin/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Refresh admin access token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.RefreshTokenReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "summary": "Admin Refresh Token",
                "tags": [
                    "Admin Auth"
                ]
            }
        },
        "/admin/users": {
            "get": {
                "description": "Get list of all registered users in system",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "items": {
                                "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.User"
                            },
                            "type": "array"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List All Users",
                "tags": [
                    "Admin User Management"
                ]
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "description": "Create user with specific role (user, seller, admin)",
                "parameters": [
                    {
                        "description": "Create User Request",
                        "in": "body",
                        "name": "request",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.RegisterReq"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Admin Create User",
                "tags": [
                    "Admin User Management"
                ]
            }
        },
        "/admin/users/{id}": {
            "delete": {
                "description": "Delete a user by ID",
                "parameters": [
                    {
                        "description": "User ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Delete User",
                "tags": [
                    "Admin User Management"
                ]
            },
            "get": {
                "description": "Get detailed information of a specific user",
                "parameters": [
                    {
                        "description": "User ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "additionalProperties": {
                                "type": "string"
                            },
                            "type": "object"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get User Detail",
                "tags": [
                    "Admin User Management"
                ]
            }
        }
    },
    "definitions": {
        "github_com_l0ng7h0r_ecommerce_internal_domain.AuthResponse": {
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "roles": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "user_id": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.Category": {
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.LoginReq": {
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            },
            "required": [
                "email",
                "password"
            ],
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.Order": {
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "logistic_branch": {
                    "type": "string"
                },
                "order_items": {
                    "items": {
                        "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.OrderItem"
                    },
                    "type": "array"
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.OrderItem": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "product": {
                    "$ref": "#/definitions/github_com_l0ng7h0r_ecommerce_internal_domain.Product"
                },
                "product_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.RefreshTokenReq": {
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            },
            "required": [
                "refresh_token"
            ],
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.RegisterReq": {
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "description": "Optional, default to \"user\"",
                    "type": "string"
                }
            },
            "required": [
                "email",
                "password"
            ],
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.UpdateOrderStatusReq": {
            "properties": {
                "status": {
                    "type": "string"
                }
            },
            "required": [
                "status"
            ],
            "type": "object"
        },
        "github_com_l0ng7h0r_ecommerce_internal_domain.User": {
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "roles": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "updated_at": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "internal_handler_admin.createCategoryReq": {
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ],
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "in": "header",
            "name": "Authorization",
            "type": "apiKey"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "Admin Management Portal",
	Description:      "API สำหรับผู้ดูแลระบบ: จัดการผู้ใช้ หมวดหมู่สินค้า ออเดอร์ทั้งหมด",
	InfoInstanceName: "admin",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
